CREATE TABLE `order_info` (
  `id`                    bigint(20)     NOT NULL          AUTO_INCREMENT COMMENT '编号',
  `consignee`             varchar(100)   DEFAULT NULL      COMMENT '收货人',
  `consignee_tel`         varchar(20)    DEFAULT NULL      COMMENT '收件人电话',
  `final_total_amount`    decimal(16,2)  DEFAULT NULL      COMMENT '总金额',
  `order_status`          varchar(20)    DEFAULT NULL      COMMENT '订单状态',
  `user_id`               bigint(20)     DEFAULT NULL      COMMENT '用户id',
  `delivery_address`      varchar(1000)  DEFAULT NULL      COMMENT '送货地址',
  `order_comment`         varchar(200)   DEFAULT NULL      COMMENT '订单备注',
  `out_trade_no`          varchar(50)    DEFAULT NULL      COMMENT '订单交易编号（第三方支付用)',
  `trade_body`            varchar(200)   DEFAULT NULL      COMMENT '订单描述(第三方支付用)',
  `create_time`           datetime       DEFAULT NULL      COMMENT '创建时间',
  `operate_time`          datetime       DEFAULT NULL      COMMENT '操作时间',
  `expire_time`           datetime       DEFAULT NULL      COMMENT '失效时间',
  `tracking_no`           varchar(100)   DEFAULT NULL      COMMENT '物流单编号',
  `parent_order_id`       bigint(20)     DEFAULT NULL      COMMENT '父订单编号',
  `img_url`               varchar(200)   DEFAULT NULL      COMMENT '图片路径',
  `province_id`           int(20)        DEFAULT NULL      COMMENT '地区',
  `benefit_reduce_amount` decimal(16,2)  DEFAULT NULL      COMMENT '优惠金额',
  `original_total_amount` decimal(16,2)  DEFAULT NULL      COMMENT '原价金额',
  `feight_fee`            decimal(16,2)  DEFAULT NULL      COMMENT '运费',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3841 DEFAULT CHARSET=utf8 COMMENT='订单表 订单表';